# Prometheus設定ファイル
# Ai-semble v2 システム監視用

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aisemble-v2'
    environment: 'production'

# アラートルール設定
rule_files:
  - "alert_rules.yml"

# アラートマネージャー設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# スクレイプ設定
scrape_configs:
  # Ai-semble Orchestrator
  - job_name: 'aisemble-orchestrator'
    static_configs:
      - targets: ['orchestrator:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    
  # Ai-semble LLM Service
  - job_name: 'aisemble-llm'
    static_configs:
      - targets: ['llm-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Ai-semble Vision Service
  - job_name: 'aisemble-vision'
    static_configs:
      - targets: ['vision-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Ai-semble NLP Service
  - job_name: 'aisemble-nlp'
    static_configs:
      - targets: ['nlp-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Ai-semble Data Processor
  - job_name: 'aisemble-data-processor'
    static_configs:
      - targets: ['data-processor:8084']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Node Exporter (システムメトリクス)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
  # Podman/cAdvisor (コンテナメトリクス)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    
  # Prometheus自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# リモート書き込み設定（オプション）
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# ストレージ設定
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB